### ISSUE TITLE
Getting it to work with WSL

### ISSUE THREAD

**Issue by sla-te** [4ch1m/intellij-ansible-lint#17] opened 2024-04-03 17:03 UTC
I created two scripts:

`ansible-lint.sh`
```sh
#!/bin/bash
source ~/.virtualenvs/ansible_playbooks/bin/activate
ansible-lint ${@}
```
`ansible-lint-wsl.bat`
```bat
@echo off
wsl ./ansible-lint.sh %*
set "exit_code=%errorlevel%"
EXIT /B %exit_code%
```
I specified the absolute path to `ansible-lint-wsl.bat` within the plugin and the test works:
![image](https://github.com/4ch1m/intellij-ansible-lint/assets/22568014/8bc78c83-7af9-4118-8fca-365f74197140)

When I now though open a playbook file I keep getting "Received an unexpected return code from Ansible Lint". Given the script appears to work when I call it manually:
![image](https://github.com/4ch1m/intellij-ansible-lint/assets/22568014/bd57edc3-a4f5-401f-8100-2bc3bcd0d48c)
Maybe this could be an easy fix?

(https://github.com/4ch1m/intellij-ansible-lint/issues/3 seemed to have the same problem)

**Comment by 4ch1m** [comment] 2024-04-03 17:20
Duplicate of #3

**Comment by sla-te** [comment] 2024-04-03 17:21
Bro, maybe you have at least a hint? Are you checking the exit code somewhere? lol

**Closed as completed by 4ch1m** 2024-04-03 17:20 UTC

**Comment by 4ch1m** [comment] 2024-04-03 17:42
> Bro, maybe you have at least a hint? Are you checking the exit code somewhere? lol

Dude, check issue #3 and #8.
I don't (want to) use WSL; so I can't give you support for it.
This project is open-source... obviously.
You're welcome to contribute with a pull-request.
